[package]
name = "orly-server"
version = "0.1.0"
authors = ["Longor1996 <lalongok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# cdrs = "2.3.1"
# elasticsearch = "7.6.1-alpha.1"

pretty_env_logger = "0.4.0"
rusqlite = {version = "0.22.0", features = ["bundled"]}
tokio = { version = "0.2", features = ["macros"] }
futures = "0.3.4"

uuid = { version = "0.8", features = ["serde", "v4"] }
serde = {version = "1.0.106", features = ["derive"]}
serde_json = "1.0.51"
warp = "0.2.2"
