name: Build Project

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ${{ github.repository }}  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: c-hive/gha-npm-cache@v1
    - run: npm install
    
    - run: npm run build
    
    - name: Rust Cache
      # You may pin to the exact commit or the version.
      # uses: Swatinem/rust-cache@a4a1d8e7a62068f6210b419d94a9198cecfea0d9
      uses: Swatinem/rust-cache@v1.0.1
    
    - name: Build
      run: cargo build --verbose
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: orlytalk
        path: |
          ${{env.GITHUB_WORKSPACE}}/target/release/*
          !${{env.GITHUB_WORKSPACE}}/target/release/.fingerprint
          !${{env.GITHUB_WORKSPACE}}/target/release/build
          !${{env.GITHUB_WORKSPACE}}/target/release/deps
          !${{env.GITHUB_WORKSPACE}}/target/release/examples
          !${{env.GITHUB_WORKSPACE}}/target/release/incremental
          !${{env.GITHUB_WORKSPACE}}/target/release/.cargo-lock
