name: Build Project

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ${{ github.repository }}
  MODE: release 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: c-hive/gha-npm-cache@v1
    - run: npm install
    
    - run: npm run build
    
    - name: Rust Cache
      # You may pin to the exact commit or the version.
      # uses: Swatinem/rust-cache@a4a1d8e7a62068f6210b419d94a9198cecfea0d9
      uses: Swatinem/rust-cache@v1.0.1
    
    - name: Build
      run: cargo build --${{MODE}} --verbose
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: orlytalk
        path: |
          ${{github.workspace}}/target/${{MODE}}/*
          !${{github.workspace}}/target/${{MODE}}/.fingerprint
          !${{github.workspace}}/target/${{MODE}}/build
          !${{github.workspace}}/target/${{MODE}}/deps
          !${{github.workspace}}/target/${{MODE}}/examples
          !${{github.workspace}}/target/${{MODE}}/incremental
          !${{github.workspace}}/target/${{MODE}}/.cargo-lock
